# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'Valley Quest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Valley Quest
  pod 'Parse'
  pod 'SCLAlertView'
  pod 'BEMCheckBox'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Google/Analytics'
  pod 'NPSegmentedControl'

  target 'Valley QuestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Valley QuestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
